---
abstract: 'Put social media links into your website'
author:
  - 'Nigel Horne <njh@bandsman.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-SocialMedia
no_index:
  directory:
    - t
    - inc
requires:
  CGI::Lingua: 0
  I18N::LangTags::Detect: 0
  Test::More: 0.82
  Test::NoWarnings: 0
version: 0.05
