---
abstract: 'Put social media links into your website'
author:
  - 'Nigel Horne <njh@bandsman.co.uk>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7, CPAN::Meta::Converter version 2.142690'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-SocialMedia
no_index:
  directory:
    - t
    - inc
requires:
  CGI::Info: '0.1'
  CGI::Lingua: '0.26'
  I18N::LangTags::Detect: '0'
  LWP::UserAgent: '0'
  Test::Most: '0'
  Test::NoWarnings: '0'
  perl: '5.006002'
resources:
  repository: git://github.com/nigelhorne/HTML-SocialMedia.git
version: '0.21'
